stages:
  - build
  - staging
  - release

variables:
  PROJECT_DEV_NAME: open-genes-dev
  PROJECT_STAGE_NAME: open-genes-stage
  PROJECT_NAME: open-genes

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
  paths:
    - app/common/vendor/
    - node_modules/

build:
  stage: build
  tags:
    - docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker run --rm -v $PWD/app:/app composer install
    - docker run --rm -v $PWD:/var/www catchdigital/node-sass npm run sass
  artifacts:
    paths:
      - app/common/vendor/
      - app/genes/assets/css/style.css
      - app/genes/assets/css/style.css.map
  when: manual

deploy-dev:
  extends: .deploy
  environment:
    name: develop
  variables:
    PROJECT_DIR: /var/www/${PROJECT_DEV_NAME}
    PROJECT_DOTENV: ${DROPLET_DEV_DOTENV}

deploy-stage:
  extends: .deploy
  environment:
    name: stage
  variables:
    PROJECT_DIR: /var/www/${PROJECT_STAGE_NAME}
    PROJECT_DOTENV: ${DROPLET_STAGE_DOTENV}

deploy-prod:
  extends: .deploy
  stage: release
  environment:
    name: production
  variables:
    PROJECT_DIR: /var/www/${PROJECT_NAME}
    PROJECT_DOTENV: ${DROPLET_PROD_DOTENV}
  only:
    - master
    - develop # todo temporary while open-genes.com is not a real production

.deploy:
  stage: staging
  dependencies:
    - build
  image: instrumentisto/rsync-ssh
  script:
    - rsync -zhrl -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' app/ ${DROPLET_USER}@${DROPLET_IP}:${PROJECT_DIR}/app/
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${DROPLET_USER}@${DROPLET_IP} "php ${PROJECT_DIR}/app/common/console/yii.php migrate --interactive=0 --migrationPath=@yii/rbac/migrations,@common/migrations"
  before_script:
    - mkdir ~/.ssh
    - echo ${PROJECT_DOTENV} | base64 -d > app/.env
    - echo ${DROPLET_KEY} | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - mkdir -p app/cms/runtime/assets || true
    - mkdir -p app/genes/runtime/assets || true
  cache: {}
  when: manual
